### ISSUE TITLE
문제 분할

### ISSUE THREAD

**Issue by Kdonghs** [kangwon-univ-BE-1/Monty-Hall-Problem-Simulation#1]
## Description
문제 분할

## Tasks

- [x] 문객체 만드는 사람
- [x] 랜덤으로 초기 선택을 구현하는 사람
- [x] 선택을 변경했을 경우 확률을 구하는 사람
- [x] 선택을 변경하지 경우 확률을 구하는 사람

**Comment by jjh4450** [comment]
제가 문 객체 하겠습니다!

**Comment by peacefullyquietly** [comment]
선택 변경했을 경우 확률 하겠습니다!

**Comment by suno-boy** [comment]
선택을 변경하지 경우 확률을 구하는 사람 하겠습니다!

**Comment by sunandrabbit** [comment]
랜덤으로 초기선택을 구현하는 사람
